#!/usr/bin/env bash
# collect.sh — Collect phase artifacts and generate walkthrough
set -euo pipefail

CHANGE_ID="${1:?Usage: collect.sh <change-id>}"
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
SKILL_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
PROJECT_ROOT="$(cd "$SKILL_DIR/../../.." && pwd)"
CHANGE_DIR="$PROJECT_ROOT/openspec/changes/$CHANGE_ID"

if [ ! -d "$CHANGE_DIR" ]; then
  echo "Error: $CHANGE_DIR not found"
  exit 1
fi

OUTPUT="$CHANGE_DIR/walkthrough.md"

# Read artifacts and compose walkthrough
SPEC_DELTA="$CHANGE_DIR/spec-delta.md"
DESIGN="$CHANGE_DIR/design.md"
TASK_LIST="$CHANGE_DIR/task-list.md"
CONTRACT_DIFF="$CHANGE_DIR/contract-diff.md"

echo "# Walkthrough — Change $CHANGE_ID" > "$OUTPUT"
echo "" >> "$OUTPUT"
echo "> Auto-generated by AI-DLC Walkthrough System" >> "$OUTPUT"
echo "" >> "$OUTPUT"

if [ -f "$SPEC_DELTA" ]; then
  echo "## Understand" >> "$OUTPUT"
  head -20 "$SPEC_DELTA" >> "$OUTPUT"
  echo "" >> "$OUTPUT"
fi

if [ -f "$DESIGN" ]; then
  echo "## Plan" >> "$OUTPUT"
  head -30 "$DESIGN" >> "$OUTPUT"
  echo "" >> "$OUTPUT"
fi

if [ -f "$CONTRACT_DIFF" ]; then
  echo "## Contract Diff" >> "$OUTPUT"
  cat "$CONTRACT_DIFF" >> "$OUTPUT"
  echo "" >> "$OUTPUT"
fi

echo "---" >> "$OUTPUT"
echo "Generated: $(date -u +%Y-%m-%dT%H:%M:%SZ)" >> "$OUTPUT"

echo "✓ Walkthrough generated: $OUTPUT"
