[plugin]
name = "protobuf"
display_name = "Protocol Buffers"
file_extension = ".proto"
mime_type = "text/x-protobuf"
default_outdir = "protobuf"
output_filename_template = "{name}.proto"
package_name_default = "types"

[features]
enums = true
allOf = true
oneOf = true
anyOf = true
nullable = true
readOnly = true
writeOnly = true
format_hints = ["date-time", "uuid", "email", "uri", "double"]
