from __future__ import annotations

import os
import re
from dataclasses import dataclass
from pathlib import Path

import yaml


@dataclass(frozen=True)
class ComponentSpec:
    id: str
    kind: str
    owns: str
    fr_prefix: str
    tech: str
    label: str
    description: str


@dataclass(frozen=True)
class CrossCutSpec:
    id: str
    paths: tuple[str, ...]
    label: str
    description: str


COMPONENTS: tuple[ComponentSpec, ...] = (
    ComponentSpec(
        id="native",
        kind="mobile",
        owns="apps/native",
        fr_prefix="NATIVE",
        tech="react-native | flutter",
        label="Mobile App",
        description="iOS/Android cross-platform (RN/Flutter)",
    ),
    ComponentSpec(
        id="desktop",
        kind="desktop",
        owns="apps/desktop",
        fr_prefix="DESKTOP",
        tech="electron | tauri",
        label="Desktop App",
        description="Cross-platform desktop (Electron/Tauri)",
    ),
    ComponentSpec(
        id="web",
        kind="frontend",
        owns="apps/web",
        fr_prefix="WEB",
        tech="react | vue | svelte",
        label="Web Frontend",
        description="Browser SPA/SSR (React/Vue/Svelte)",
    ),
    ComponentSpec(
        id="backend",
        kind="service",
        owns="apps/backend",
        fr_prefix="BE",
        tech="python | node | go",
        label="Backend Service",
        description="HTTP API/microservice (Python/Node/Go)",
    ),
    ComponentSpec(
        id="wxa",
        kind="mini-program",
        owns="apps/wxa",
        fr_prefix="WXA",
        tech="miniprogram",
        label="WeChat Mini-Program",
        description="WeChat ecosystem mini-program",
    ),
    ComponentSpec(
        id="mya",
        kind="mini-program",
        owns="apps/mya",
        fr_prefix="MYA",
        tech="miniprogram",
        label="Alipay Mini-Program",
        description="Alipay ecosystem mini-program",
    ),
    ComponentSpec(
        id="tta",
        kind="mini-program",
        owns="apps/tta",
        fr_prefix="TTA",
        tech="miniprogram",
        label="TikTok Mini-Program",
        description="TikTok/Douyin ecosystem mini-program",
    ),
)


COMPONENT_BY_ID: dict[str, ComponentSpec] = {c.id: c for c in COMPONENTS}


CROSS_CUTTING: tuple[CrossCutSpec, ...] = (
    CrossCutSpec(
        id="contracts",
        paths=("aidlc/contracts/CHANGELOG.md",),
        label="Interface Contracts",
        description="API/event contracts and changelog",
    ),
    CrossCutSpec(
        id="shared",
        paths=("aidlc/packages/shared",),
        label="Shared Types",
        description="Cross-component shared types package",
    ),
    CrossCutSpec(
        id="openspec",
        paths=(),
        label="OpenSpec Changes",
        description="OpenSpec change proposals",
    ),
    CrossCutSpec(
        id="cross_stack_features",
        paths=(),
        label="Cross-Stack BDD",
        description="End-to-end BDD features across components",
    ),
    CrossCutSpec(
        id="cross_stack_tests",
        paths=("aidlc/tests/contract", "aidlc/tests/cross-stack"),
        label="Cross-Stack Tests",
        description="Contract tests and cross-stack integration tests",
    ),
    CrossCutSpec(
        id="provider",
        paths=(
            "aidlc/providers/tcb/provider.yaml",
            "aidlc/providers/tcb/deployment.yaml",
            "aidlc/providers/tcb/preview.yaml",
        ),
        label="Cloud Provider",
        description="TCB (Tencent CloudBase) provider config",
    ),
    CrossCutSpec(
        id="tools",
        paths=(
            "aidlc/tools/deploy_stack.py",
            "aidlc/tools/contract_diff.py",
            "aidlc/tools/generate_shared.py",
        ),
        label="Tooling Scripts",
        description="deploy_stack / contract_diff / generate_shared stubs",
    ),
)


CROSS_CUTTING_BY_ID: dict[str, CrossCutSpec] = {c.id: c for c in CROSS_CUTTING}


TCB_PROVIDER_YAML = """provider:
  name: tcb
  display_name: Tencent CloudBase
  default: true
  version: 3.0.0

storage:
  object_storage: cloudbase-storage
  document_db: docdb
  relational_db: mysql
  cdn: tencent-cloud-cdn
"""

TCB_DEPLOYMENT_YAML = """environments:
  preview:
    orchestrator: deploy_stack
    strategy: unified
    ttl: 24h
  staging:
    orchestrator: deploy_stack
  production:
    orchestrator: deploy_stack
    pre_conditions:
      - human-approval-gate
"""

TCB_PREVIEW_YAML = """preview:
  orchestrator: deploy_stack
  strategy: unified
  ttl: 24h
  auto_cleanup: true
  db_sandbox: true
"""

TOOL_STUB = """#!/usr/bin/env python3
\"\"\"Stub — auto-generated by cdh scaffold.\"\"\"
import sys


def main():
    print(f"{__file__}: not yet implemented")
    sys.exit(1)


if __name__ == "__main__":
    main()
"""

ALIYUN_PROVIDER_YAML = """provider:
  name: aliyun
  display_name: Alibaba Cloud
  default: false
  version: 3.0.0

storage:
  object_storage: oss
  document_db: mongodb
  relational_db: rds-mysql
  cdn: aliyun-cdn
"""

ALIYUN_DEPLOYMENT_YAML = """environments:
  preview:
    orchestrator: deploy_stack
    strategy: unified
    ttl: 24h
  staging:
    orchestrator: deploy_stack
  production:
    orchestrator: deploy_stack
    pre_conditions:
      - human-approval-gate
"""

ALIYUN_PREVIEW_YAML = """preview:
  orchestrator: deploy_stack
  strategy: unified
  ttl: 24h
  auto_cleanup: true
  db_sandbox: true
"""

GITHUB_ACTIONS_CI_YAML = """name: AIDLC Quality Gates
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v5
        with:
          python-version: "3.14"
      - name: Install cdh
        run: pip install cdh
      - name: Validate spec quality
        run: cdh aidlc validate --format json
      - name: Contract compat check
        run: |
          cdh aidlc tools install
          python aidlc/tools/contract_diff.py --base origin/main --head HEAD \\
            --project-root .
      - name: Run tests
        run: |
          pip install pytest pytest-cov pytest-bdd
          pytest --cov --cov-fail-under=80
"""

PRE_COMMIT_CONFIG_YAML = """repos:
  - repo: local
    hooks:
      - id: aidlc-validate
        name: aidlc validate
        entry: cdh aidlc validate
        language: system
        pass_filenames: false
        always_run: true
      - id: aidlc-contract-diff
        name: aidlc contract diff
        entry: python aidlc/tools/contract_diff.py --base origin/main --head HEAD
        language: system
        pass_filenames: false
        always_run: true
"""

CONFTEST_PY = '''"""Auto-generated by cdh scaffold."""
import json
from pathlib import Path
import pytest


def pytest_addoption(parser):
    parser.addoption("--base-url", default="http://localhost:8080", help="Base URL for e2e tests")
    parser.addoption("--api-url", default="", help="API URL")
    parser.addoption("--stack-url", default="", help="Stack preview URL")


@pytest.fixture
def base_url(request):
    return request.config.getoption("--base-url")


@pytest.fixture
def api_url(request):
    return request.config.getoption("--api-url") or request.config.getoption("--base-url")
'''

PYPROJECT_TOML = """[tool.pytest.ini_options]
minversion = "8.0"
testpaths = ["tests"]
python_files = ["test_*.py"]
markers = [
    "unit: unit tests",
    "integration: integration tests",
    "e2e: end-to-end tests",
    "contract: contract tests",
    "cross_stack: cross-stack tests",
    "positive: positive scenarios",
    "negative: negative/error scenarios",
    "edge: edge case scenarios",
]
"""

DOCKER_COMPOSE_YAML = """version: "3.9"
services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: aidlc
      POSTGRES_USER: aidlc
      POSTGRES_PASSWORD: aidlc
    ports:
      - "5432:5432"
    tmpfs: /var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  minio:
    image: minio/minio:latest
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: aidlc
      MINIO_ROOT_PASSWORD: aidlc123456
    ports:
      - "9000:9000"
      - "9001:9001"
"""

ENV_LOCAL = """BACKEND_URL=http://localhost:8080
DATABASE_URL=postgresql://aidlc:aidlc@localhost:5432/aidlc
REDIS_URL=redis://localhost:6379/0
S3_ENDPOINT=http://localhost:9000
S3_ACCESS_KEY=aidlc
S3_SECRET_KEY=aidlc123456
"""

GITIGNORE_CONTENT = """# Python
__pycache__/
*.py[cod]
*.egg-info/
dist/
build/
.venv/
venv/
*.egg

# Node
node_modules/
.next/
dist/
.nuxt/
.cache/

# IDE
.vscode/
.idea/
*.swp
*.swo
*~

# OS
.DS_Store
Thumbs.db

# CDH
.cdh/
"""

CHANGELOG_MD = "# Changelog\n\n## [0.1.0] - Initial scaffold\n\n- Project created via cdh scaffold\n"




AGENTS_HEADER = """# AGENTS.md — {project_name}

<!-- ═══════════════════════════════════════════════════════════
     Generated from ai-dlc-skill/SKILL.md — do not edit manually.
     Rebuild with `cdh scaffold` to sync with the source skill.
     ═══════════════════════════════════════════════════════════ -->

"""

PROJECT_RULES_BLOCK = """
<!-- ═══════════════════════════════════════════════════════════
     Project Rules
     ═══════════════════════════════════════════════════════════ -->

## Project Rules

1. Intent → Spec (EARS) → BDD → Design (DAG) → TDD Red-Green-Refactor → Deploy
2. Contract-first for cross-component changes (`aidlc/contracts/`)
3. FR namespaces: NATIVE|DESKTOP|WEB|BE|WXA|MYA|TTA (apps/) + INT (aidlc/contracts/)
4. Quality gates: coverage ≥80%, BDD 100%, 0 vulns, no TODO, backward-compat contracts
5. Cross-stack e2e mandatory for changes affecting ≥2 components
6. Never commit secrets; never force-push to main/master
7. Chinese for user communication, English for code
8. Run lint/typecheck/test after non-trivial edits
"""

MDC_FRONTMATTER = """---
description: AI-DLC Core Lifecycle Rules
globs: ["*"]
---

"""

REQUIREMENTS_MD = """# {project_name}

## Intent

{description}

## Stack Topology

Monorepo multi-component stack with the following components:

| Component | FR Prefix | Default Language | Default UI Framework | Directory |
|-----------|-----------|-----------------|---------------------|-----------|
{component_table}

## Quality Gates

| Gate | Threshold |
|------|-----------|
| Unit/integration coverage | >= 80% |
| BDD scenarios pass | 100% |
| Contract tests pass | 100% |
| Cross-stack e2e pass | 100% |
| Security vulns | 0 |

Default cloud provider: TCB (Tencent CloudBase).
"""


def _mkdir(path: Path) -> None:
    path.mkdir(parents=True, exist_ok=True)


def _gitkeep(path: Path) -> None:
    keep = path / ".gitkeep"
    if not keep.exists():
        keep.write_text("", encoding="utf-8")


def _write(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content.lstrip("\n"), encoding="utf-8")


def _build_agents_component_table(active: list[ComponentSpec]) -> str:
    rows = []
    for c in active:
        rows.append(f"| {c.fr_prefix:7s} | {c.owns:20s} |")
    rows.append("| INT      | aidlc/contracts/, aidlc/packages/shared/ |")
    return "\n".join(rows)


def _read_skill_body(skill_path: Path) -> str:
    """Read SKILL.md and strip YAML frontmatter, return body only."""
    if not skill_path.exists():
        return ""
    raw = skill_path.read_text(encoding="utf-8")
    body = re.sub(r'^---[\s\S]*?\n---\n?', '', raw)
    return body.strip()


def _write_symlink(target: Path, link_path: Path) -> None:
    """Create a relative symlink link_path → target."""
    link_path.parent.mkdir(parents=True, exist_ok=True)
    if link_path.is_symlink() or link_path.exists():
        link_path.unlink()
    rel = os.path.relpath(target, link_path.parent)
    link_path.symlink_to(rel)


def _write_agents_and_claude_md(
    root: Path,
    project_name: str,
    description: str,
    active: list[ComponentSpec],
) -> None:
    # Read AI-DLC body from SKILL.md
    skill_path = root / "ai-dlc-skill" / "SKILL.md"
    skill_body = _read_skill_body(skill_path)

    if not skill_body:
        skill_body = (
            "## AI-DLC v4.0.0 — Master Orchestrator\n\n"
            "AI-Driven Development Lifecycle for monorepo multi-component stacks.\n"
        )

    component_table = _build_agents_component_table(active)

    # ── AGENTS.md (physical file, primary project charter) ──
    agents_content = (
        AGENTS_HEADER.format(project_name=project_name)
        + skill_body
        + PROJECT_RULES_BLOCK
        + "\n## Components\n\n"
        + "| Prefix | Directory |\n"
        + "|--------|-----------|\n"
        + component_table
        + "\n"
    )
    _write(root / "AGENTS.md", agents_content)

    # ── Symlinks to AGENTS.md for engine-native discovery ──
    symlinks = [
        root / "CLAUDE.md",
        root / ".clinerules",
        root / ".github" / "copilot-instructions.md",
    ]
    for link_path in symlinks:
        _write_symlink(root / "AGENTS.md", link_path)

    # ── .cursor/rules/ai-dlc-core.mdc (needs frontmatter) ──
    cursor_dir = root / ".cursor" / "rules"
    cursor_dir.mkdir(parents=True, exist_ok=True)
    mdc_content = (
        MDC_FRONTMATTER
        + skill_body
        + PROJECT_RULES_BLOCK
    )
    (cursor_dir / "ai-dlc-core.mdc").write_text(mdc_content.lstrip("\n"), encoding="utf-8")


def _component_to_dict(c: ComponentSpec) -> dict:
    out = {
        "id": c.id,
        "kind": c.kind,
        "tech": c.tech,
        "owns": c.owns,
        "fr_prefix": c.fr_prefix,
    }
    return out


def _build_project_yaml(
    active: list[ComponentSpec],
    cross_cutting_ids: list[str],
    name: str = "",
    description: str = "",
) -> dict:
    cross_cutting: dict = {"fr_prefix": "INT"}
    if "contracts" in cross_cutting_ids:
        cross_cutting["contracts"] = "aidlc/contracts/"
    if "shared" in cross_cutting_ids:
        cross_cutting["shared_types"] = "aidlc/packages/shared/"
    doc: dict = {
        "name": name,
        "description": description,
        "stack": {
            "topology": "monorepo",
            "components": [_component_to_dict(c) for c in active],
            "cross_cutting": cross_cutting,
        },
    }
    return doc


def _build_component_table(active: list[ComponentSpec]) -> str:
    if not active:
        return "| (none)       | -             | -                 | -                   | -                   |"
    return "\n".join(
        f"| {c.id:8s} | {c.fr_prefix + '-FR-*':14s} | {'-':17s} | {'-':21s} | {c.owns:20s} |"
        for c in active
    )


def _scaffold_component(c: ComponentSpec, root: Path) -> None:
    comp_dir = root / c.owns
    _mkdir(comp_dir / "src")
    if c.kind == "mini-program":
        _mkdir(comp_dir / "tests" / "e2e")
        _gitkeep(comp_dir / "tests" / "e2e")
    else:
        _mkdir(comp_dir / "tests" / "unit")
        _mkdir(comp_dir / "tests" / "integration")
        _mkdir(comp_dir / "tests" / "e2e")
        _gitkeep(comp_dir / "tests" / "unit")
        _gitkeep(comp_dir / "tests" / "integration")
        _gitkeep(comp_dir / "tests" / "e2e")
    _mkdir(comp_dir / "features")
    _gitkeep(comp_dir / "features")
    _gitkeep(comp_dir / "src")
    _gitkeep(comp_dir)


def _scaffold_cross_cutting(cross_ids: list[str], root: Path) -> None:
    for cid in cross_ids:
        spec = CROSS_CUTTING_BY_ID.get(cid)
        if spec is None:
            continue
        for p in spec.paths:
            target = root / p
            if p.endswith((".yaml", ".py", ".md")):
                if p == "aidlc/contracts/CHANGELOG.md":
                    _write(target, CHANGELOG_MD)
                elif p == "aidlc/providers/tcb/provider.yaml":
                    _write(target, TCB_PROVIDER_YAML)
                elif p == "aidlc/providers/tcb/deployment.yaml":
                    _write(target, TCB_DEPLOYMENT_YAML)
                elif p == "aidlc/providers/tcb/preview.yaml":
                    _write(target, TCB_PREVIEW_YAML)
                elif p.startswith("aidlc/tools/") and p.endswith(".py"):
                    _write(target, TOOL_STUB)
                    target.chmod(0o755)
                else:
                    _write(target, "")
            else:
                _mkdir(target)
                _gitkeep(target)


def _scaffold_ci_templates(root: Path, component_ids: list[str] | None = None) -> None:
    ci_dir = root / ".github" / "workflows"
    ci_dir.mkdir(parents=True, exist_ok=True)
    (ci_dir / "aidlc-ci.yaml").write_text(GITHUB_ACTIONS_CI_YAML, encoding="utf-8")
    (root / ".pre-commit-config.yaml").write_text(PRE_COMMIT_CONFIG_YAML, encoding="utf-8")


def _scaffold_test_templates(root: Path, component_ids: list[str] | None = None) -> None:
    _write(root / "conftest.py", CONFTEST_PY)
    _write(root / "pyproject.toml", PYPROJECT_TOML)


def _scaffold_local_env(root: Path) -> None:
    _write(root / "docker-compose.yaml", DOCKER_COMPOSE_YAML)
    _write(root / ".env.local", ENV_LOCAL)
    _write(root / ".env.example", ENV_LOCAL)


def _scaffold_provider_templates(root: Path, provider: str | None) -> None:
    if provider is None or provider == "tcb":
        return
    provider_dir = root / "aidlc" / "providers" / provider
    provider_dir.mkdir(parents=True, exist_ok=True)
    if provider == "aliyun":
        _write(provider_dir / "provider.yaml", ALIYUN_PROVIDER_YAML)
        _write(provider_dir / "deployment.yaml", ALIYUN_DEPLOYMENT_YAML)
        _write(provider_dir / "preview.yaml", ALIYUN_PREVIEW_YAML)


def _write_project_yaml(
    root: Path,
    project_name: str,
    active: list[ComponentSpec],
    cross_cutting_ids: list[str],
    description: str,
) -> None:
    _write(
        root / "aidlc" / "project.yaml",
        yaml.dump(
            _build_project_yaml(active, cross_cutting_ids, name=project_name, description=description),
            default_flow_style=False,
        ),
    )
    _write(
        root / "aidlc" / "requirements.md",
        REQUIREMENTS_MD.format(
            project_name=project_name,
            description=description or f"AI-DLC monorepo project: {project_name}",
            component_table=_build_component_table(active),
        ),
    )
    _write(root / ".gitignore", GITIGNORE_CONTENT)
    _write(root / "aidlc" / "CHANGELOG.md", CHANGELOG_MD)


def init_dlc_project(
    workspace_root: Path,
    project_name: str,
    description: str = "",
    with_ci: bool = False,
    with_tests: bool = False,
    with_local: bool = False,
    provider: str | None = None,
) -> bool:
    """Scaffold project metadata only (no apps/*, no cross-cutting dirs)."""

    root = workspace_root.resolve()
    _write_project_yaml(
        root=root,
        project_name=project_name,
        active=[],
        cross_cutting_ids=[],
        description=description,
    )
    _write_agents_and_claude_md(root, project_name, description, [])
    if with_ci:
        _scaffold_ci_templates(root)
    if with_tests:
        _scaffold_test_templates(root)
    if with_local:
        _scaffold_local_env(root)
    if provider:
        _scaffold_provider_templates(root, provider)
    return True


def scaffold_dlc_project(
    workspace_root: Path,
    project_name: str,
    components: list[str] | None = None,
    description: str = "",
    with_ci: bool = False,
    with_tests: bool = False,
    with_local: bool = False,
    provider: str | None = None,
) -> bool:
    """Scaffold a full ai-dlc-skill monorepo project structure.

    Application components are optional — when omitted only cross-cutting
    items (contracts, shared types, openspec, etc.) are created.
    Components can be added later with add_component().

    Args:
        components: list of component ids (e.g. ["web", "backend"]).
                   If None or empty, only cross-cutting items are scaffolded.

    Returns True if scaffolding was performed.

    Raises ValueError if any component id is unknown.
    """
    if components is None:
        components = []

    unknown = [c for c in components if c not in COMPONENT_BY_ID]
    if unknown:
        raise ValueError(
            f"Unknown component id(s): {', '.join(unknown)}. "
            f"Valid ids: {', '.join(COMPONENT_BY_ID)}."
        )

    root = workspace_root.resolve()
    active = [COMPONENT_BY_ID[cid] for cid in components]
    all_cross_ids = [
        c.id for c in CROSS_CUTTING if c.id not in ("provider", "tools")
    ]

    _write_project_yaml(
        root=root,
        project_name=project_name,
        active=active,
        cross_cutting_ids=all_cross_ids,
        description=description,
    )

    for c in active:
        _scaffold_component(c, root)

    _scaffold_cross_cutting(all_cross_ids, root)
    _write_agents_and_claude_md(root, project_name, description, active)

    if with_ci:
        _scaffold_ci_templates(root, components)
    if with_tests:
        _scaffold_test_templates(root, components)
    if with_local:
        _scaffold_local_env(root)
    if provider:
        _scaffold_provider_templates(root, provider)

    return True


def _regenerate_agents_and_claude_md(root: Path) -> None:
    project_yaml = root / "aidlc" / "project.yaml"
    if not project_yaml.exists():
        return
    data = yaml.safe_load(project_yaml.read_text(encoding="utf-8")) or {}
    name = data.get("name", root.name)
    description = data.get("description", "")
    components = data.get("stack", {}).get("components", []) or []
    active = []
    for c in components:
        spec = COMPONENT_BY_ID.get(c.get("id", ""))
        if spec:
            active.append(spec)
    _write_agents_and_claude_md(root, name, description, active)


def add_component(
    workspace_root: Path,
    component_id: str,
) -> bool:
    """Add a single application component to an existing project.

    Creates apps/<owns>/{src,tests/unit,tests/e2e,features} with
    .gitkeep files and updates aidlc/project.yaml's stack.components list.

    Returns True if the component was added, False if it was already
    present. Raises ValueError on unknown component id.
    """
    spec = COMPONENT_BY_ID.get(component_id)
    if spec is None:
        raise ValueError(
            f"Unknown component id: {component_id}. "
            f"Valid ids: {', '.join(COMPONENT_BY_ID)}."
        )

    root = workspace_root.resolve()
    project_yaml = root / "aidlc" / "project.yaml"
    if not project_yaml.exists():
        raise FileNotFoundError(
            f"aidlc/project.yaml not found at {root}. Run 'cdh project init' first."
        )

    data = yaml.safe_load(project_yaml.read_text(encoding="utf-8")) or {}
    components = data.get("stack", {}).get("components", []) or []
    if any(c.get("id") == component_id for c in components):
        return False

    _scaffold_component(spec, root)

    components.append(_component_to_dict(spec))
    data["stack"]["components"] = components
    project_yaml.write_text(
        yaml.dump(data, default_flow_style=False),
        encoding="utf-8",
    )
    _regenerate_agents_and_claude_md(root)
    return True


def add_cross_cutting(
    workspace_root: Path,
    cross_id: str,
) -> bool:
    """Add a single cross-cutting item to an existing project.

    Creates the relevant directories/files and updates aidlc/project.yaml
    so that stack.cross_cutting references the new path.

    Returns True if the item was added, False if it was already present.
    Raises ValueError on unknown cross-cutting id.
    """
    spec = CROSS_CUTTING_BY_ID.get(cross_id)
    if spec is None:
        raise ValueError(
            f"Unknown cross-cutting id: {cross_id}. "
            f"Valid ids: {', '.join(CROSS_CUTTING_BY_ID)}."
        )

    root = workspace_root.resolve()
    project_yaml = root / "aidlc" / "project.yaml"
    if not project_yaml.exists():
        raise FileNotFoundError(
            f"aidlc/project.yaml not found at {root}. Run 'cdh project init' first."
        )

    cross_paths = [root / p for p in spec.paths]
    if all(p.exists() for p in cross_paths):
        return False

    _scaffold_cross_cutting([cross_id], root)

    data = yaml.safe_load(project_yaml.read_text(encoding="utf-8")) or {}
    cross_cutting = data.setdefault("stack", {}).setdefault("cross_cutting", {})
    if cross_id == "contracts":
        cross_cutting["contracts"] = "aidlc/contracts/"
    elif cross_id == "shared":
        cross_cutting["shared_types"] = "packages/shared/"

    project_yaml.write_text(
        yaml.dump(data, default_flow_style=False),
        encoding="utf-8",
    )
    _regenerate_agents_and_claude_md(root)
    return True


def check_dlc_project(workspace_root: Path) -> dict:
    """Check whether a directory is a valid AIDC project and return diagnostics.

    Returns a dict with keys:
      valid        — bool, whether the project is minimally valid
      name         — str or None
      path         — str (resolved root)
      components   — list of component ids
      has_cdh      — bool
      suggestions  — list of human-readable improvement suggestions
    """
    root = workspace_root.resolve()
    result: dict = {
        "valid": True,
        "name": None,
        "path": str(root),
        "components": [],
        "has_cdh": False,
        "suggestions": [],
    }

    project_yaml = root / "aidlc" / "project.yaml"
    if not project_yaml.exists():
        result["suggestions"].append(
            f"Missing aidlc/project.yaml — run 'cdh aidlc init {root}' first"
        )
        result["valid"] = False
        return result

    try:
        data = yaml.safe_load(project_yaml.read_text(encoding="utf-8"))
    except Exception as e:
        result["suggestions"].append(f"Invalid YAML in aidlc/project.yaml: {e}")
        result["valid"] = False
        return result

    if not isinstance(data, dict):
        result["suggestions"].append("aidlc/project.yaml is not a valid YAML mapping")
        result["valid"] = False
        return result

    name = data.get("name", "")
    if not name:
        result["suggestions"].append("Missing 'name' field in aidlc/project.yaml")
        result["valid"] = False
        name = root.name
    result["name"] = name

    components = data.get("stack", {}).get("components", [])
    if not components:
        result["suggestions"].append(
            "No components defined in stack.components — "
            "use 'cdh aidlc add-component' to add one"
        )
    else:
        ids = []
        for c in components:
            cid = c.get("id", "")
            if not cid:
                result["suggestions"].append(
                    "A component entry is missing its 'id' field"
                )
                continue
            ids.append(cid)
            if cid not in COMPONENT_BY_ID:
                result["suggestions"].append(
                    f"Unknown component id '{cid}' — expected one of: "
                    f"{', '.join(COMPONENT_BY_ID)}"
                )
            else:
                owns = COMPONENT_BY_ID[cid].owns
                if not (root / owns).exists():
                    result["suggestions"].append(
                        f"Component '{cid}' directory '{owns}/' not found on disk"
                    )
        result["components"] = ids

    cross_cutting = data.get("stack", {}).get("cross_cutting", {})
    if isinstance(cross_cutting, dict):
        for key, path_val in cross_cutting.items():
            if isinstance(path_val, str) and not (root / path_val).exists():
                result["suggestions"].append(
                    f"Cross-cutting '{key}' path '{path_val}' not found on disk"
                )

    from cdh.project_loader import CdhProjectLoader
    result["has_cdh"] = CdhProjectLoader.find_cdh_dir(root) is not None
    if not result["has_cdh"]:
        result["suggestions"].append(
            ".cdh/ not found — run 'cdh aidlc init' to set up project state"
        )

    return result


__all__ = [
    "COMPONENTS",
    "COMPONENT_BY_ID",
    "CROSS_CUTTING",
    "CROSS_CUTTING_BY_ID",
    "ComponentSpec",
    "CrossCutSpec",
    "init_dlc_project",
    "scaffold_dlc_project",
    "add_component",
    "add_cross_cutting",
    "check_dlc_project",
    "_regenerate_agents_and_claude_md",
]
