from __future__ import annotations

from pathlib import Path
from typing import Optional

import yaml


SKILL_NAME = "ai-dlc-skill"

SKILL_YAML_COMPONENTS = [
    {"id": "native", "kind": "mobile", "tech": "react-native | flutter", "owns": "apps/native", "fr_prefix": "NATIVE"},
    {"id": "desktop", "kind": "desktop", "tech": "electron | tauri", "owns": "apps/desktop", "fr_prefix": "DESKTOP"},
    {"id": "web", "kind": "frontend", "tech": "react | vue | svelte", "owns": "apps/web", "fr_prefix": "WEB"},
    {"id": "backend", "kind": "service", "tech": "python | node | go", "owns": "apps/backend", "fr_prefix": "BE"},
    {"id": "wxa", "kind": "mini-program", "tech": "miniprogram", "owns": "apps/wxa", "fr_prefix": "WXA"},
    {"id": "mya", "kind": "mini-program", "tech": "miniprogram", "owns": "apps/mya", "fr_prefix": "MYA"},
    {"id": "tta", "kind": "mini-program", "tech": "miniprogram", "owns": "apps/tta", "fr_prefix": "TTA"},
]

TCB_PROVIDER_YAML = """provider:
  name: tcb
  display_name: Tencent CloudBase
  default: true
  version: 3.0.0
"""

TCB_DEPLOYMENT_YAML = """environments:
  preview:
    orchestrator: deploy_stack
    strategy: unified
    ttl: 24h
  staging:
    orchestrator: deploy_stack
  production:
    orchestrator: deploy_stack
    pre_conditions:
      - human-approval-gate
"""

TCB_PREVIEW_YAML = """preview:
  orchestrator: deploy_stack
  strategy: unified
  ttl: 24h
  auto_cleanup: true
  db_sandbox: true
"""

TOOL_STUB = """#!/usr/bin/env python3
\"\"\"Stub — auto-generated by cdh scaffold.\"\"\"
import sys


def main():
    print(f"{__file__}: not yet implemented")
    sys.exit(1)


if __name__ == "__main__":
    main()
"""

GITIGNORE_CONTENT = """# Python
__pycache__/
*.py[cod]
*.egg-info/
dist/
build/
.venv/
venv/
*.egg

# Node
node_modules/
.next/
dist/
.nuxt/
.cache/

# IDE
.vscode/
.idea/
*.swp
*.swo
*~

# OS
.DS_Store
Thumbs.db

# CDH
.cdh/
"""

CHANGELOG_MD = "# Changelog\n\n## [0.1.0] - Initial scaffold\n\n- Project created via cdh scaffold\n"

REQUIREMENTS_MD = """# {project_name}

## Intent

{description}

## Stack Topology

Monorepo multi-component stack with the following components:

| Component | FR Prefix | Directory |
|-----------|-----------|-----------|
{component_table}

## Quality Gates

| Gate | Threshold |
|------|-----------|
| Unit/integration coverage | >= 80% |
| BDD scenarios pass | 100% |
| Contract tests pass | 100% |
| Cross-stack e2e pass | 100% |
| Security vulns | 0 |

Default cloud provider: TCB (Tencent CloudBase).
"""


def _detect_dlc_skill(workspace_root: Path) -> bool:
    from cdha.skills.loader import SkillLoader
    loader = SkillLoader(workspace_root)
    return loader.get(SKILL_NAME) is not None


def _mkdir(path: Path) -> None:
    path.mkdir(parents=True, exist_ok=True)


def _gitkeep(path: Path) -> None:
    keep = path / ".gitkeep"
    if not keep.exists():
        keep.write_text("", encoding="utf-8")


def _write(path: Path, content: str) -> None:
    path.write_text(content.lstrip("\n"), encoding="utf-8")


def scaffold_dlc_project(
    workspace_root: Path,
    project_name: str,
    components: Optional[list[str]] = None,
    description: str = "",
) -> bool:
    """Scaffold a full ai-dlc-skill monorepo project structure.

    Returns True if scaffolding was performed, False if ai-dlc-skill
    is not available and the project was left untouched.
    """
    if not _detect_dlc_skill(workspace_root):
        return False

    root = workspace_root.resolve()

    if components is not None:
        active = [c for c in SKILL_YAML_COMPONENTS if c["id"] in components]
    else:
        active = list(SKILL_YAML_COMPONENTS)

    # --- project.yaml ---
    project_yaml = {
        "stack": {
            "topology": "monorepo",
            "components": [
                {
                    "id": c["id"],
                    "kind": c["kind"],
                    "tech": c["tech"],
                    "owns": c["owns"],
                    "fr_prefix": c["fr_prefix"],
                }
                for c in active
            ],
            "cross_cutting": {
                "fr_prefix": "INT",
                "contracts": "contracts/",
                "shared_types": "packages/shared/",
            },
        }
    }
    _write(root / "project.yaml", yaml.dump(project_yaml, default_flow_style=False))

    # --- requirements.md ---
    component_rows = "\n".join(
        f"| {c['id']:8s} | {c['fr_prefix'] + '-FR-*':14s} | {c['owns']:20s} |"
        for c in active
    )
    _write(
        root / "requirements.md",
        REQUIREMENTS_MD.format(
            project_name=project_name,
            description=description or f"AI-DLC monorepo project: {project_name}",
            component_table=component_rows,
        ),
    )

    # --- .gitignore ---
    _write(root / ".gitignore", GITIGNORE_CONTENT)

    # --- apps/{component}/ src/ tests/ features/ ---
    for c in active:
        comp_dir = root / c["owns"]
        _mkdir(comp_dir / "src")
        _mkdir(comp_dir / "tests" / "unit")
        _mkdir(comp_dir / "tests" / "e2e")
        _mkdir(comp_dir / "features")
        _gitkeep(comp_dir / "src")
        _gitkeep(comp_dir / "tests" / "unit")
        _gitkeep(comp_dir / "tests" / "e2e")
        _gitkeep(comp_dir / "features")
        _gitkeep(comp_dir)

    # --- contracts/{api,events}/ + CHANGELOG.md ---
    _mkdir(root / "contracts" / "api")
    _mkdir(root / "contracts" / "events")
    _gitkeep(root / "contracts" / "api")
    _gitkeep(root / "contracts" / "events")
    _write(root / "contracts" / "CHANGELOG.md", CHANGELOG_MD)

    # --- packages/shared/ ---
    _mkdir(root / "packages" / "shared")
    _gitkeep(root / "packages" / "shared")

    # --- features/cross-stack/ ---
    _mkdir(root / "features" / "cross-stack")
    _gitkeep(root / "features" / "cross-stack")

    # --- tests/{contract,cross-stack}/ ---
    _mkdir(root / "tests" / "contract")
    _mkdir(root / "tests" / "cross-stack")
    _gitkeep(root / "tests" / "contract")
    _gitkeep(root / "tests" / "cross-stack")

    # --- openspec/changes/ ---
    _mkdir(root / "openspec" / "changes")
    _gitkeep(root / "openspec" / "changes")

    # --- providers/tcb/ ---
    _mkdir(root / "providers" / "tcb")
    _write(root / "providers" / "tcb" / "provider.yaml", TCB_PROVIDER_YAML)
    _write(root / "providers" / "tcb" / "deployment.yaml", TCB_DEPLOYMENT_YAML)
    _write(root / "providers" / "tcb" / "preview.yaml", TCB_PREVIEW_YAML)

    # --- tools/ stub scripts ---
    _mkdir(root / "tools")
    for tool in ("deploy_stack.py", "contract_diff.py", "generate_shared.py"):
        _write(root / "tools" / tool, TOOL_STUB)
        (root / "tools" / tool).chmod(0o755)

    return True
