[plugin]
name = "rust"
display_name = "Rust"
file_extension = ".rs"
mime_type = "text/x-rust"
default_outdir = "rust"
output_filename_template = "{name}.rs"
package_name_default = "types"

[features]
enums = true
allOf = true
oneOf = true
anyOf = true
nullable = true
readOnly = true
writeOnly = true
format_hints = ["date-time", "uuid", "email", "uri", "double"]
