#!/usr/bin/env bash
# generate-context.sh — Generate AI-DLC-CONTEXT.md for brownfield projects
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
OUTPUT="$PROJECT_ROOT/aidlc/AI-DLC-CONTEXT.md"

echo "# AI-DLC Context — $(basename "$PROJECT_ROOT")"
echo ""
echo "Auto-generated on $(date -u +%Y-%m-%dT%H:%M:%SZ)"
echo ""

# 1. Component discovery
echo "## Components"
echo ""
for comp_dir in "$PROJECT_ROOT"/apps/*/; do
  name="$(basename "$comp_dir")"
  pkg="$comp_dir/package.json"
  if [ -f "$pkg" ]; then
    framework="$(python3 -c "import json; d=json.load(open('$pkg')); print(d.get('framework','?'))" 2>/dev/null || echo "?")"
    echo "- **$name**: $framework"
  else
    echo "- **$name**: (no package.json)"
  fi
done
echo ""

# 2. API surface
echo "## API Surface"
echo ""
if [ -d "$PROJECT_ROOT/aidlc/contracts/api" ]; then
  find "$PROJECT_ROOT/aidlc/contracts/api" -name "*.yaml" -o -name "*.yml" | while read -r f; do
    echo "- $(basename "$f")"
  done
else
  echo "(No contract files discovered)"
fi
echo ""

# 3. Dependency map (simplified)
echo "## Dependency Map"
echo ""
echo '```mermaid'
echo 'graph LR'
for comp_dir in "$PROJECT_ROOT"/apps/*/; do
  name="$(basename "$comp_dir")"
  pkg="$comp_dir/package.json"
  if [ -f "$pkg" ]; then
    python3 -c "
import json
d=json.load(open('$pkg'))
for dep in d.get('dependencies',{}):
    print(f'  {name} -->|depends| {dep}')
for dep in d.get('devDependencies',{}):
    pass
" 2>/dev/null || true
  fi
done
echo '```'
echo ""

echo "---"
echo "Generated by brownfield/generate-context.sh"
