[plugin]
name = "graphql-schema"
display_name = "GraphQL Schema"
file_extension = ".graphqls"
mime_type = "application/graphql"
default_outdir = "graphql"
output_filename_template = "{name}.graphqls"
package_name_default = "types"

[features]
enums = true
allOf = true
oneOf = true
anyOf = true
nullable = true
readOnly = true
writeOnly = true
format_hints = ["date-time", "uuid", "email", "uri", "double"]
